
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace baithi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class doanhthu
{

    public int iddoanhthu { get; set; }

    public Nullable<System.DateTime> ngaykiem { get; set; }

    public string doanhthuthu { get; set; }

    public string doanhthuchi { get; set; }

}

}
