

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace baithi.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class quanlydocauEntities : DbContext
{
    public quanlydocauEntities()
        : base("name=quanlydocauEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<doanhthu> doanhthus { get; set; }

    public virtual DbSet<hang> hangs { get; set; }

    public virtual DbSet<hdchitiet> hdchitiets { get; set; }

    public virtual DbSet<hoadonsp> hoadonsps { get; set; }

    public virtual DbSet<kh_hang> kh_hang { get; set; }

    public virtual DbSet<khohang> khohangs { get; set; }

    public virtual DbSet<loai> loais { get; set; }

    public virtual DbSet<ncc> nccs { get; set; }

    public virtual DbSet<nv> nvs { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<sanpham> sanphams { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<Taikhoan> Taikhoans { get; set; }

}

}

