
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace baithi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetail
{

    public int ID { get; set; }

    public Nullable<int> idsanpham { get; set; }

    public Nullable<int> soluongmua { get; set; }

    public Nullable<decimal> tongtien { get; set; }

    public Nullable<int> idorder { get; set; }

    public string tensp { get; set; }

    public Nullable<decimal> tonghoadon { get; set; }

    public Nullable<System.DateTime> ngaymua { get; set; }

}

}
