
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace baithi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class sanpham
{

    public int IDsp { get; set; }

    public string tensp { get; set; }

    public string size { get; set; }

    public Nullable<int> loai { get; set; }

    public Nullable<int> hang { get; set; }

    public Nullable<int> soluong { get; set; }

    public string giathanh { get; set; }

    public string anh { get; set; }

    public Nullable<int> tenkho { get; set; }

    public string mota { get; set; }

}

}
